/* Palette generated by Material Palette - materialpalette.com/indigo/indigo */

export const green = "#0bba27";
export const red = "#ff4444";
export const white = "#FFFFFF";
export const lightblue = "#303F9F";
export const lightblue2 = "#3F51B5";
export const lightblue3 = "#00BCD4";
export const lightgray = "#CFD8DC";
export const gray = "#757575";
export const yellow = "#FFEB3B";
